spring:
  datasource:
    driver.class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/authenticationdb
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
        ddl-auto: create
